build_variant:
  - "qt"
  - "osmesa"  # [linux64]
  - "egl"  # [linux64]
replacements:
  all_replacements:
    - tag: 'CMake build metadata'
      glob_patterns:
        - '*.cmake'
      regex_re: '([^;\s"]+/sysroot)'
      replacement_re: '$ENV{CONDA_BUILD_SYSROOT}'
    - tag: 'CMake build metadata OSX'
      glob_patterns:
        - '*.cmake'
      regex_re: '([^;\s"]+/MacOSX\d*\.?\d*\.sdk)'
      replacement_re: '$ENV{CONDA_BUILD_SYSROOT}'
cudnn:                                            # [linux64]
  - undefined                                     # [linux64]
cuda_compiler_version:                            # [linux64]
  - None                                          # [linux64]
